#!/usr/bin/env bash
# Thomas Merkel <tm@core.io>
# The "do it first"-script, working on something else

##
## static variables
##
TM_HOME=${HOME:-'/home/tm'}
TM_ENV=${TM_HOME}'/.tm-env'

GIT_SRC_PUBLIC='git@github.com:drscream/tm-env.git'
GIT_SRC_PRIVATE='git@github.com:drscream/tm-env-private.git'

HTTP_SRC_PUBLIC='https://github.com/drscream/tm-env.git'
HTTP_SRC_PRIVATE='https://github.com/drscream/tm-env-private.git'


##
## functions
##
# simple help output
_help() {
	echo ${0}' [-u|-i] [public|private] [git|http]'
	echo -e '\nOPTIONS:'
	echo -e '\t -u: update (git pull)'
	echo -e '\t -i: initial (symlink)'
	exit 1
}

# logging
_log() {
	echo "$(date +'%Y-%m-%d %T') | ${1} | ${2}" >> ${TM_ENV}/tm-env.log
}

# link stuff
_link() {
	src=${1}
	dst=${TM_HOME}'/.'${2}

	_log 'link' "${src} ${dst}"
	test -L ${dst} || ln -sv ${src} ${dst}
}

# init the repos and symlink
_init() {
	if [ -d ${TM_ENV} ]; then
		echo -e 'The folder to the '${TM_ENV}' already exists.\nDelete it if you like to init it again.'
		#exit 1
	fi

	# get the source
	git clone ${SRC_PUBLIC} ${TM_ENV}

	# symlink all folders with .d at the end 
	find ${TM_ENV}/${1}/etc/*.d -type d | while read dir; do
		dst=$(basename ${dir})
		_link ${dir} ${dst}
	done

	# symlink all files
	find ${TM_ENV}/${1}/etc -type f | while read file; do
		if [ "$(echo ${file} | grep -c '\.d/')" -eq 0 ]; then
			dst=${file##${TM_ENV}/${1}/etc/}
			_link ${file} ${dst}
		fi
	done
}

_init_private() {
	echo
}

_update() {
#	git pull ${TM_ENV}/${1}
	echo $SRC_PRIVATE
}

_update_private() {
	echo
}


##
## main
##
if [ ${#} -ne 3 ]; then
	_help
fi

# set some basics from the parameters
case ${3} in
	git)
		SRC_PUBLIC=${GIT_SRC_PUBLIC}
		SRC_PRIVATE=${GIT_SRC_PRIVATE}
	;;
	http)
		SRC_PUBLIC=${HTTP_SRC_PUBLIC}
		SRC_PRIVATE=${HTTP_SRC_PRIVATE}
	;;
	*)
		_help
	;;
esac

# parse opts
while getopts 'u:i:' option; do
	case ${option} in
		u)
			_update ${OPTARG}
		;;
		i)
			_init ${OPTARG}
		;;
		*)
			_help
		;;
	esac
done
