#!/usr/bin/env bash
# Simple xrandr wrapper build for my needs.

auto() {
	dpCount=$(xrandr --query | egrep -c '^DP.* connected')
	if (( ${dpCount} == 2 )); then
		dock
	fi
}

dock() {
	echo "[${0##*/}] docking station mode"
	local -a DPS=( $(xrandr --listmonitors | sed -n 's|\ [0-9]:\ +\(DP[-0-9]*\)\ .*|\1|p') )
	xrandr --output eDP-1 --off \
		   --output ${DPS[1]} --right-of ${DPS[0]}
}

beamer() {
	echo "[${0##*/}] beamer mode"
	xrandr --output HDMI --auto
}

single() {
	echo "[${0##*/}] single screen mode"
}

# Main
case ${1} in
	auto) auto ;;
	dock) dock ;;
	beamer) beamer ;;
	-h|--help) echo "${0##*/} [dock|beamer|single|auto]"; exit 1 ;;
	*) auto ;;
esac
